### PR TITLE
Issue 115: Set null for name and email so whoami works on service acct

### PR DESCRIPTION
**Pull request by JesseRhoads-PD**
This should fix an issue we encountered where cloudsmith-cli can't do a whoami on a service account.

### CODE REVIEW

**Comment by chrisimcevoy** [comment]
Hey Jesse 👋 
Thanks so much for taking the time to look at this.
It looks like what's happening here is that `email` is `None` for Services, which makes sense.
(We came across this a month or two ago, and found that this Exception wouldn't be raised if we moved to click v8.0, but that isn't possible until Python 2 support has been deprecated.)
One suggestion: Rather than outputting `"email: \"Null\""`, what would you say to _not_ outputting anything for `email` if it is falsy?
Happy to co-author something to that effect if you are ok with that?

**Comment by JesseRhoads-PD** [comment]
Sure, feel free to take over and land this one differently, I just wanted to get a fix out ASAP. 
Feel free to Implement it in whatever way makes the most sense.

**Comment by chrisimcevoy** [comment]
So now for a User, `cloudsmith whoami` output will be something like:

```
Retrieving your authentication status from the API ... OK
You are authenticated as:
Chris McEvoy (slug: chris-mcevoy, email: cmcevoy@cloudsmith.io)
```

And for a Service:

```
Retrieving your authentication status from the API ... OK
You are authenticated as:
bot-manager (slug: bot-manager)
```

Does that look ok to you, Jesse?

**Comment by JesseRhoads-PD** [comment]
Yes, I put this in locally and it worked. Thanks!

**Review by chrisimcevoy — APPROVED** [review]

**Comment by JesseRhoads-PD** [comment]
Rebased and signed so it can be merged.

**Pull request merged**
